### ISSUE TITLE
App still marked as experimental

### ISSUE THREAD

**Issue by lapineige** [YunoHost-Apps/glitchsoc_ynh#102]
In Yunohost app catalog, Glitch-Soc is still marked as experimental.
@Tagadda do you feel comfortable if we change that ? :)

**Comment by Tagadda** [comment]
It's from glitch-soc README, not me :p

**Comment by lapineige** [comment]
Yeah but it's more than stable since the beginning :smile:, and it has not the same meaning in the catalog. Many people won't see it in the catalog if they search for stable apps.

**Comment by Tagadda** [comment]
Still it's just a mention is the README, not a tag in the catalog or something.

**Comment by lapineige** [comment]
Oh sorry, I was mistaken.
