### ISSUE TITLE
Failure when updating to v2024.02.14

### ISSUE THREAD

**Issue by warpKaiba** [YunoHost-Apps/glitchsoc_ynh#225]
### Describe the bug

Upgrade fails with the following. When I check lib/devise/, there is no two_factor_ldap_authenticatable.rb file there. There IS one in lib/devise/strategies/ though.

Also, the first time I tried upgrading it deleted my .env.production file so I needed to get it from a backup.

```Error: Could not upgrade glitchsoc__2: An error occurred inside the app upgrade script
Info: The operation 'Upgrade the 'glitchsoc__2' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20240216-010555-app_upgrade-glitchsoc__2' to get help
Warning: Here's an extract of the logs before the crash. It might help debugging the error:
Info: DEBUG - + patch --strip=1
Info: DEBUG - patching file app/controllers/application_controller.rb
Info: DEBUG - Hunk #1 succeeded at 84 (offset 16 lines).
Info: DEBUG - patching file config/initializers/devise.rb
Info: DEBUG - Hunk #1 succeeded at 183 (offset 3 lines).
Info: DEBUG - can't find file to patch at input line 32
Info: DEBUG - Perhaps you used the wrong -p or --strip option?
Info: DEBUG - The text leading up to this was:
Info: DEBUG - --------------------------
Info: DEBUG - |diff --git a/lib/devise/two_factor_ldap_authenticatable.rb b/lib/devise/two_factor_ldap_authenticatable.rb
Info: DEBUG - |index 065aa2de8..0eb4be10c 100644
Info: DEBUG - |--- a/lib/devise/two_factor_ldap_authenticatable.rb
Info: DEBUG - |+++ b/lib/devise/two_factor_ldap_authenticatable.rb
Info: DEBUG - --------------------------
Info: DEBUG - File to patch:
Info: DEBUG - Skip this patch? [y]
Info: DEBUG - Skipping patch.
Info: DEBUG - 2 out of 2 hunks ignored
Info: DEBUG - + ynh_die '--message=Unable to apply patches'
Info: DEBUG - + ynh_exit_properly
Error: The operation 'Upgrade the 'glitchsoc__2' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20240216-010555-app_upgrade-glitchsoc__2' to get help
```

### Context

- Hardware: Home server
- YunoHost version: 11.2.4
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: Yes I have 2 glitchsoc instances running
- Using, or trying to install package version/branch:  2024.02.14~ynh1
- If upgrading, current package version:  2023.12.18~ynh1
- 
### Steps to reproduce

yunohost app upgrade "glitchsoc__2" --no-safety-backup

### Logs

https://paste.yunohost.org/raw/wudeneride

**Comment by OniriCorpe** [comment]
Is it still relevant with the latest versions?

**Comment by warpKaiba** [comment]
> Is it still relevant with the latest versions?

I ended up fixing it myself with the fork I made, [this commit](https://github.com/YunoHost-Apps/glitchsoc_ynh/pull/226) would have fixed it as well since the problem was with the patch
