### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost-Apps/glitchsoc_ynh#58]
### Describe the bug

Update from `2022.05.13~ynh1` fails.

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.6.3
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
  - If yes, please explain:
- Using, or trying to install package version/branch:
- If upgrading, current package version: 2022.05.13~ynh1

### Steps to reproduce

- *Upgrade command*
    ```sh
    sudo yunohost app upgrade glitchsoc
    ```

### Expected behavior

*The app upgrades normally*

### [Logs](https://paste.yunohost.org/raw/boyevasidu)

**Comment by Tagadda** [comment]
```
2022-06-10 21:39:49,312: WARNING - 318  A backup archive with this name already exists.
2022-06-10 21:39:49,369: DEBUG - + ynh_die '--message=Backup failed, the upgrade process was aborted.'
2022-06-10 21:39:49,397: WARNING - Backup failed, the upgrade process was aborted.
2022-06-10 21:39:50,399: ERROR - Could not upgrade glitchsoc: An error occurred inside the app upgrade script
```
You need to delete the old backup then run the upgrade.

**Comment by xplosionmind** [comment]
> You need to delete the old backup

Thanks for helping, @Tagadda! Could you go a bit further and tell me how I can manually remove a backup?

**Comment by Tagadda** [comment]
Through the web admin, if it's still visible on the backup list.
Or via CLI, you'll need to search for the corresponding `.json` and `.tar` in `/home/yunohost.backup/`.
