### ISSUE TITLE
Level 1

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/glitchsoc_ynh#6]
Own CI result for Revision: ef1236b0da9522597a743975703c16949b989073 

Logs: https://paste.yunohost.org/afuqoyahob.coffeescript

![image](https://user-images.githubusercontent.com/30271971/118738916-74b35d00-b848-11eb-86cb-f9de46a23cc3.png)

![image](https://user-images.githubusercontent.com/30271971/118739008-a75d5580-b848-11eb-8de7-30c3840fbf9d.png)

Same as official CI

**Comment by Tagadda** [comment]
This is glitch-soc (or a dependency) blocking `domain.tld`.
So CI fails but the package will install on a normal use-case.
Any advice ? I'll probably disable the multi_install test.

**Comment by yalh76** [comment]
> Any advice ? I'll probably disable the multi_instance test.

As there are few cases where someone has too install two instance of glitchsoc, looks legit to disable multi_instance
