### ISSUE TITLE
rbenv: version 3.0.4 is not installed

### ISSUE THREAD

**Issue by junochat** [YunoHost-Apps/glitchsoc_ynh#82]
Update to 2022.10.21~ynh1 works perfectly fine -- no errors.

Running admin `tootctl` commands produces
`rbenv: version '3.0.4' is not installed (set by /var/www/glitchsoc/live/.ruby-version)`

Going through the update log, installer does indeed install 3.0.3, not 3.0.4 that is required.

### Context
Hardware: VPS
Yunohost version: 4.4.2.14
Glitch-soc version: 2022.08.01~ynh1 update through CLI

**Comment by lapineige** [comment]
Fixed by #95
